### ISSUE TITLE
bno was not declared in this scope in line 333

### ISSUE THREAD

**Issue by MMky13** [DominikN/ESP32-MPU9250-web-view#4]
Hi,
I'm trying to use the code with a mpu 9250 but I'm getting an bno was not declared error from line 333 when I try to compile the code.

**Comment by barthex** [comment]
comment line #291, there is located bno object, which is not declared when mpu9250 is used.

**Comment by DominikN** [comment]
fixed, and added GitHub Workflow to check whether firmware is building fine
